# 1. $PLUx = b$

In [24]:
# import numpy as np
from pylab import *

def swap(row1: int, row2: int, matrix: np.array) -> np.array:
    matrix[[row1, row2]] = matrix[[row2, row1]]
    return matrix

In [25]:
# test swap
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Matrix:")
print(matrix)
matrix = swap(0, 1, matrix)
print("\nMatrix After Swapping Rows:")
print(matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix After Swapping Rows:
[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [ ]:
# def get_element_index_in_range()

In [216]:
# def get_abs_max(column_index: int, matrix: np.array) -> (float, int):
#     column = matrix[:, column_index]
#     abs_column = np.abs(column)
#     partial_column = abs_column[column_index: ]
#     print(f"partial_column: {partial_column}")
#     abs_max_value = np.max(partial_column)
#     abs_max_index = np.argmax(abs_column)
#     print(f"abs_max_value: {abs_max_value}, abs_max_index: {abs_max_index}")
#     return (abs_max_value, abs_max_index)

def get_abs_max(column_index: int, matrix: np.array) -> (float, int):
    column = matrix[:, column_index]
    n = matrix.shape[0]
    abs_column = np.abs(column)
    abs_max_value = 0
    abs_max_index = column_index
    for i in range(column_index, n):
        if abs_column[i] > abs_max_value:
            abs_max_value = abs_column[i]
            abs_max_index = i
    return (abs_max_value, abs_max_index)

In [217]:
def get_l_trig_with_1_diag(matrix: np.array):
    lower_triangle_matrix = tril(matrix)
    diag_matrix = diag(diag(matrix))
    lower_triangle_matrix_minus_diag = lower_triangle_matrix - diag_matrix
    lower_triangle_matrix_with_1_diag = lower_triangle_matrix_minus_diag + eye(matrix.shape[0])
    return lower_triangle_matrix_with_1_diag

In [218]:
# def partial_pivot(p: array, matrix: array, column_index: int):
#     print(f"beginning， colum index: \n{column_index} \n ----------- \n p: \n {p}, --- \n matrix: \n {matrix}")
#     matrix_original = copy.deepcopy(matrix)
#     matrix = copy.deepcopy(matrix[column_index:, column_index:])
#     print(f"sub matrix:\n {matrix}")
#     column_index_backup = column_index
#     column_index = 0
#     (abs_max_value, abs_max_index) = get_abs_max(column_index = column_index, matrix = matrix)
#     n = matrix.shape[0] - 1 # matrix must be n by n
#     # print(abs_max_index)
#     p = swap(row1 = column_index, row2 = abs_max_index, matrix = p)
#     matrix = swap(row1 = column_index, row2 = abs_max_index, matrix = matrix)
    
#     matrix_original[column_index_backup:, column_index_backup:] = matrix
#     print(f"p: \n {p}, --- \n matrix: \n {matrix}")
#     return (p, matrix)

def partial_pivot(p: array, matrix: array, column_index: int):
    (abs_max_value, abs_max_index) = get_abs_max(column_index = column_index, matrix = matrix)
    n = matrix.shape[0] - 1 # matrix must be n by n
    p = swap(row1 = column_index, row2 = abs_max_index, matrix = p)
    matrix = swap(row1 = column_index, row2 = abs_max_index, matrix = matrix)
    return (p, matrix)

In [219]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
p = eye(3)
partial_pivot(p = p, matrix = matrix, column_index = 0)

(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]),
 array([[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]]))

In [220]:
import copy
def single_raw_LU_decomposite(matrix: array, column_index: int):
    if matrix.dtype != 'float':
        matrix = matrix.astype(float)
    
    head_ele = matrix[column_index][column_index]
    head_raw = matrix[column_index]
    if head_ele == 0:
        return
    
    n = matrix.shape[0]
    for i in range(column_index + 1, n):
        curr_row = matrix[i]
        row_head = curr_row[column_index]
        if row_head == 0:
            continue
        change_factor = - row_head / head_ele
        # print(f"change_factor: {change_factor}")
        # row_to_change = copy.deepcopy(curr_row[column_index:])
        row_to_change = copy.deepcopy(curr_row)
        row_to_change = change_factor * head_raw + row_to_change
        
        chagned_row = curr_row[:column_index]
        chagned_row = np.append(chagned_row, -change_factor)
        # chagned_row.append(change_factor)
        
        # chagned_row += row_to_change[column_index + 1:]
        chagned_row = np.append(chagned_row, row_to_change[column_index + 1:])
        matrix[i] = chagned_row
    
    return matrix

In [221]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
single_raw_LU_decomposite(matrix=matrix, column_index = 1)

array([[ 1. ,  2. ,  3. ],
       [ 4. ,  5. ,  6. ],
       [ 7. ,  1.6, -0.6]])

In [224]:
def perform_PLU_decomposite(A: array) -> (array, array, array, array): #p, L, U, A
    n = A.shape[0]
    p = eye(n)
    matrix = copy.deepcopy(A)
    for i in range(n):
        p, matrix = partial_pivot(p = p, matrix = matrix, column_index = i)
        matrix = single_raw_LU_decomposite(matrix = matrix, column_index = i)
    
    return (p, matrix, get_l_trig_with_1_diag(matrix), np.triu(matrix))

In [225]:
matrix = np.array([[2, 1, 5], [4, 4, -4], [1, 3, 1]])
matrix, perform_PLU_decomposite(A = matrix)

(array([[ 2,  1,  5],
        [ 4,  4, -4],
        [ 1,  3,  1]]),
 (array([[0., 1., 0.],
         [0., 0., 1.],
         [1., 0., 0.]]),
  array([[ 4.  ,  4.  , -4.  ],
         [ 0.25,  2.  ,  2.  ],
         [ 0.5 , -0.5 ,  8.  ]]),
  array([[ 1.  ,  0.  ,  0.  ],
         [ 0.25,  1.  ,  0.  ],
         [ 0.5 , -0.5 ,  1.  ]]),
  array([[ 4.,  4., -4.],
         [ 0.,  2.,  2.],
         [ 0.,  0.,  8.]])))