In [3]:
import numpy as np

# Create a sample matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print original matrix
print("Original Matrix:")
print(matrix)

# Indices of rows you want to swap
row1, row2 = 0, 1  # For example, swapping the first and second rows

# Swapping rows
matrix[[row1, row2]] = matrix[[row2, row1]]

# Print modified matrix
print("\nMatrix After Swapping Rows:")
print(matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix After Swapping Rows:
[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [13]:
import numpy as np

# Create a sample matrix with both positive and negative values
matrix = np.array([[1, -7, 3], [4, -100, -6], [-7, 2, 9]])

# Column index from which to find the absolute max value
column_index = 1  # for example, the second column

# Access the column
column = matrix[:, column_index]

# Apply absolute value
abs_column = np.abs(column)

# Find the maximum value in the absolute values of the column
abs_max_value = np.max(abs_column)

# Find the index (row number) of the maximum value in the absolute values of the column
abs_max_index = np.argmax(abs_column)

print(f"Absolute maximum value in column {column_index}: {abs_max_value}")
print(f"Index of the absolute maximum value (row number): {abs_max_index}")


Absolute maximum value in column 1: 100
Index of the absolute maximum value (row number): 1


In [14]:
def get_abs_max(column_index: int, matrix: np.array):
    column = matrix[:, column_index]
    abs_column = np.abs(column)
    abs_max_value = np.max(abs_column)
    abs_max_index = np.argmax(abs_column)
    return (abs_max_value, abs_max_index)

In [16]:
matrix = np.array([[1, -7, 3], [4, -100, -6], [-7, 2, 9]])
column_index = 1
result = get_abs_max(column_index = column_index, matrix=matrix)

In [17]:
print(f"max: {result[0]}, index: {result[1]}")

max: 100, index: 1


In [22]:
import numpy as np

# Create a sample matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Use np.tril() to get the lower triangular part of the matrix
lower_triangle_matrix = np.tril(matrix)

print("Original Matrix:")
print(matrix)
print("\nLower Triangular Part:")
print(lower_triangle_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Lower Triangular Part:
[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [27]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix.shape

(3, 3)

In [26]:
from pylab import *
matrix = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diag(matrix)

array([1, 5, 9])

In [29]:
def get_l_trig_with_1_diag(matrix: np.array):
    lower_triangle_matrix = tril(matrix)
    diag_matrix = diag(diag(matrix))
    lower_triangle_matrix_minus_diag = lower_triangle_matrix - diag_matrix
    lower_triangle_matrix_with_1_diag = lower_triangle_matrix_minus_diag + eye(matrix.shape[0])
    return lower_triangle_matrix_with_1_diag

In [30]:
matrix = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
get_l_trig_with_1_diag(matrix)

array([[1., 0., 0.],
       [4., 1., 0.],
       [7., 8., 1.]])

In [31]:
l = [0, 1, 2, 3, 4]
l[1:]

[1, 2, 3, 4]

In [ ]:
l2 = l[1:]

In [34]:
import numpy as np

# Original matrix
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(f"Original matrix: \n {matrix}")
# New submatrix to replace a part of the original matrix
new_submatrix = np.array([[21, 22], [23, 24]])

# Define the location in the original matrix where the new submatrix will be placed
# Here, we're replacing the bottom-right 2x2 section
matrix[2:, 2:] = new_submatrix

print("Modified Matrix:")
print(matrix)


Original matrix: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 21 22]
 [13 14 23 24]]


In [39]:
import numpy as np

# Example 4x4 matrix
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(f"Original matrix: \n {matrix}")

# Extract bottom-right 2x2 submatrix
submatrix = matrix[0:, 0:]

print("Submatrix:")
print(submatrix)

Original matrix: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Submatrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
